name: URL Checker

on:
  schedule:
    - cron: "0 0 * * *"  # 每天午夜运行
  push:
    branches:
      - main

jobs:
  check-urls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run URL checker
      env:
        URLS: ${{ secrets.URLS }}  # 从 secrets 读取
      run: python check_urls.py

    - name: Show Git status
      run: |
        git status
        git log --oneline

    - name: Commit results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add url_check_results.csv
        git commit -m 'Update URL check results'
        git push
