name: Schedule URL Visit

on:
  schedule:
    - cron: '0 */2 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  visit-url:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        TARGET_URL: ${{ secrets.TARGET_URL }}
      run: python main.py
